name: Deploy React to Azure Static Web App

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get GitHub ID Token
        uses: actions/github-script@v7
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_ROCK_0BA1A0703 }}
          action: upload
          app_location: /
          api_location: ""
          output_location: dist
          github_id_token: ${{ steps.idtoken.outputs.result }}
